goog.provide('odd.examples.data');

odd.examples.simpleOscillator_ = "eyJlcXVhdGlvbnMiOlsieCcgPSBhICogeSIsInknID0gYiAqIHgiXSwidmFyaWFibGVzIjp7ImluaXRpYWwiOlt7Im5hbWUiOiJ4KDApIiwidmFsdWUiOjUsInVuaXQiOiJtIiwidHlwZSI6InNsaWRlciIsIm1pbiI6LTUsIm1heCI6NSwic3RlcCI6MC4xfSx7Im5hbWUiOiJ5KDApIiwidmFsdWUiOjUsInVuaXQiOiJtIiwidHlwZSI6InNsaWRlciIsIm1pbiI6LTUsIm1heCI6NSwic3RlcCI6MC4xfV0sInBhcmFtZXRlcnMiOlt7Im5hbWUiOiJhIiwidmFsdWUiOjEsInR5cGUiOiJzbGlkZXIiLCJtaW4iOjAsIm1heCI6Mywic3RlcCI6MC4xfSx7Im5hbWUiOiJiIiwidmFsdWUiOi0xLCJ0eXBlIjoic2xpZGVyIiwibWluIjotMywibWF4IjowLCJzdGVwIjowLjF9XX0sImdyYXBoLW9wdGlvbnMiOnsibGVmdCI6LTEwLCJyaWdodCI6MTAsInRvcCI6MTAsImJvdHRvbSI6LTEwfX0%3D";

odd.examples.dampedOscillator_ = "eyJlcXVhdGlvbnMiOlsieCcgPSB2IiwidicgPSAtIHcgKiB3ICogeCAtIDIgKiB6ZXRhICogdyAqIHYiXSwidmFyaWFibGVzIjp7ImluaXRpYWwiOlt7Im5hbWUiOiJ4KDApIiwidmFsdWUiOjIsInVuaXQiOiJtIiwidHlwZSI6InNsaWRlciIsIm1pbiI6LTUsIm1heCI6NSwic3RlcCI6MC4xfSx7Im5hbWUiOiJ2KDApIiwidmFsdWUiOjAsInVuaXQiOiJtL3MiLCJ0eXBlIjoic2xpZGVyIiwibWluIjotMjAsIm1heCI6MjAsInN0ZXAiOjF9XSwicGFyYW1ldGVycyI6W3sibmFtZSI6InciLCJ2YWx1ZSI6MC41LCJ0eXBlIjoic2xpZGVyIiwibWluIjowLCJtYXgiOjAuNSwic3RlcCI6MC4wMDV9LHsibmFtZSI6InpldGEiLCJ2YWx1ZSI6LTAuMDUsInR5cGUiOiJzbGlkZXIiLCJtaW4iOi0wLjEsIm1heCI6MC4xLCJzdGVwIjowLjAxfV19LCJncmFwaC1vcHRpb25zIjp7ImxlZnQiOi0xMDAsInJpZ2h0IjoxMDAsInRvcCI6LTEzLCJib3R0b20iOjEzfX0%3D";

odd.examples.data = {
  'Simple Harmonic Oscillator': odd.examples.simpleOscillator_,
  'Damped Harmonic Oscillator': odd.examples.dampedOscillator_
};