// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../odd/odd.js', ['odd'], ['goog.math.Range', 'odd.odesolver.OdeSolver', 'odd.problem.Problem', 'odd.solution.Solution', 'odd.ui.Graph'], false);
goog.addDependency('../../../../odd/odesolver/odesolver.js', ['odd.odesolver.OdeSolver', 'odd.odesolver.RungeKuttaMethod'], ['goog.math.Range', 'odd.problem.Problem', 'odd.solution.Solution'], false);
goog.addDependency('../../../../odd/odesolver/odesolver_test.js', ['odd.odesolver.odesolverTest'], ['goog.testing.jsunit'], false);
goog.addDependency('../../../../odd/problem/problem.js', ['odd.problem.Problem'], ['odd.solution.Point'], false);
goog.addDependency('../../../../odd/solution/point.js', ['odd.solution.Point'], ['goog.math.Rect'], false);
goog.addDependency('../../../../odd/solution/solution.js', ['odd.solution.Solution', 'odd.solution.Solution.NewDataEvent'], ['goog.array', 'goog.events.EventTarget', 'goog.math.Range', 'goog.math.Rect', 'goog.structs.AvlTree', 'odd.solution.Point'], false);
goog.addDependency('../../../../odd/ui/graph.js', ['odd.ui.Graph'], ['goog.array', 'goog.graphics', 'goog.graphics.Path', 'goog.graphics.Stroke', 'goog.math.Coordinate', 'odd.solution.Solution', 'odd.solution.Solution.NewDataEvent'], false);
