// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../odd/data/vector.js', ['odd.data.Vector'], ['goog.array'], false);
goog.addDependency('../../../../odd/data/vector_test.js', ['odd.data.vectorTest'], ['goog.testing.jsunit', 'odd.data.Vector'], false);
goog.addDependency('../../../../odd/graph/coordinatemapper.js', ['odd.graph.CoordinateMapper'], [], false);
goog.addDependency('../../../../odd/graph/coordinatemapper_test.js', ['odd.graph.coordinatemapperTest'], ['goog.math.Box', 'goog.math.Range', 'goog.testing.jsunit', 'odd.graph.CoordinateMapper'], false);
goog.addDependency('../../../../odd/graph/graph.js', ['odd.graph.Graph'], ['goog.graphics', 'goog.graphics.Path', 'goog.graphics.Stroke', 'goog.math.Box', 'goog.ui.Component', 'odd.graph.CoordinateMapper', 'odd.graph.GraphAxes', 'odd.system.OdeSystem.EventTypes'], false);
goog.addDependency('../../../../odd/graph/graphaxes.js', ['odd.graph.GraphAxes'], ['goog.graphics.Path', 'goog.math'], false);
goog.addDependency('../../../../odd/labels/labels.js', ['odd.labels.Labels'], ['goog.array', 'odd.labels.VariableLabel'], false);
goog.addDependency('../../../../odd/labels/variablelabel.js', ['odd.labels.VariableLabel'], [], false);
goog.addDependency('../../../../odd/odd.js', ['odd'], ['goog.math.Range', 'odd.data.Vector', 'odd.graph.Graph', 'odd.labels.Labels', 'odd.labels.VariableLabel', 'odd.problem.Problem', 'odd.problem.ProblemGenerator', 'odd.solution.Solution', 'odd.system.OdeSystem'], false);
goog.addDependency('../../../../odd/problem/problem.js', ['odd.problem.Problem'], ['odd.solution.Point'], false);
goog.addDependency('../../../../odd/problem/problem_test.js', ['odd.problem.problemTest'], ['goog.testing.jsunit', 'odd.data.Vector', 'odd.problem.Problem', 'odd.solution.Point'], false);
goog.addDependency('../../../../odd/problem/problemgenerator.js', ['odd.problem.ProblemGenerator'], ['odd.data.Vector', 'odd.problem.Problem'], false);
goog.addDependency('../../../../odd/problem/problemgenerator_test.js', ['odd.problem.problemGeneratorTest'], ['goog.testing.jsunit', 'odd.data.Vector', 'odd.problem.Problem', 'odd.solution.Point'], false);
goog.addDependency('../../../../odd/solution/point.js', ['odd.solution.Point'], ['odd.data.Vector'], false);
goog.addDependency('../../../../odd/solution/point_test.js', ['odd.solution.pointTest'], ['goog.testing.jsunit', 'odd.data.Vector', 'odd.solution.Point'], false);
goog.addDependency('../../../../odd/solution/solution.js', ['odd.solution.Solution', 'odd.solution.Solution.NewDataEvent'], ['goog.array', 'goog.events.EventTarget', 'goog.math.Range', 'goog.structs.AvlTree', 'odd.solution.Point'], false);
goog.addDependency('../../../../odd/solution/solution_test.js', ['odd.solution.solutionTest'], ['goog.math.Range', 'goog.testing.jsunit', 'odd.solution.Point', 'odd.solution.Solution'], false);
goog.addDependency('../../../../odd/solver/solver.js', ['odd.solver.EulerMethod', 'odd.solver.RungeKuttaMethod', 'odd.solver.Solver'], ['goog.math.Range', 'odd.problem.Problem', 'odd.solution.Point', 'odd.solution.Solution'], false);
goog.addDependency('../../../../odd/system/odesystem.js', ['odd.system.OdeSystem', 'odd.system.OdeSystem.EventTypes'], ['goog.events.EventTarget', 'goog.math.Range', 'goog.structs.Map', 'odd.data.Vector', 'odd.labels.Labels', 'odd.problem.Problem', 'odd.problem.ProblemGenerator', 'odd.solution.Solution', 'odd.solution.Solution.NewDataEvent', 'odd.solver.Solver', 'odd.system.ProblemSolutionPair'], false);
goog.addDependency('../../../../odd/system/problemsolutionpair.js', ['odd.system.ProblemSolutionPair'], ['odd.problem.Problem'], false);
