// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../odd/odd.js', ['odd'], ['goog.math.Range', 'odd.odesolver.Euler', 'odd.odesolver.OdeSolver', 'odd.problem.Problem', 'odd.solution.Solution', 'odd.solution.Vector', 'odd.ui.Graph'], false);
goog.addDependency('../../../../odd/odesolver/odesolver.js', ['odd.odesolver.Euler', 'odd.odesolver.OdeSolver', 'odd.odesolver.RungeKuttaMethod'], ['goog.math.Range', 'odd.problem.Problem', 'odd.solution.Solution'], false);
goog.addDependency('../../../../odd/odesolver/odesolver_test.js', ['odd.odesolver.odesolverTest'], ['goog.testing.jsunit'], false);
goog.addDependency('../../../../odd/problem/problem.js', ['odd.problem.Problem'], ['odd.solution.Point', 'odd.solution.Vector'], false);
goog.addDependency('../../../../odd/solution/point.js', ['odd.solution.Point'], ['odd.solution.Vector'], false);
goog.addDependency('../../../../odd/solution/solution.js', ['odd.solution.Solution', 'odd.solution.Solution.NewDataEvent'], ['goog.array', 'goog.events.EventTarget', 'goog.math.Range', 'goog.structs.AvlTree', 'odd.solution.Point'], false);
goog.addDependency('../../../../odd/solution/solution_test.js', ['odd.solution.solutionTest'], ['goog.math.Range', 'goog.testing.jsunit', 'odd.solution.Point', 'odd.solution.Solution'], false);
goog.addDependency('../../../../odd/solution/vector.js', ['odd.solution.Vector'], ['goog.array'], false);
goog.addDependency('../../../../odd/solution/vector_test.js', ['odd.solution.vectorTest'], ['goog.testing.jsunit', 'odd.solution.Vector'], false);
goog.addDependency('../../../../odd/ui/coordinatemapper.js', ['odd.ui.CoordinateMapper'], ['goog.math.Box', 'goog.math.Range'], false);
goog.addDependency('../../../../odd/ui/coordinatemapper_test.js', ['odd.ui.coordinatemapperTest'], ['goog.math.Box', 'goog.math.Range', 'goog.testing.jsunit', 'odd.ui.CoordinateMapper'], false);
goog.addDependency('../../../../odd/ui/graph.js', ['odd.ui.Graph'], ['goog.array', 'goog.color', 'goog.graphics', 'goog.graphics.Font', 'goog.graphics.Path', 'goog.graphics.Stroke', 'goog.math.Box', 'odd.solution.Solution', 'odd.solution.Solution.NewDataEvent', 'odd.ui.CoordinateMapper', 'odd.ui.GraphAxes'], false);
goog.addDependency('../../../../odd/ui/graphaxes.js', ['odd.ui.GraphAxes'], ['goog.graphics.Path', 'goog.math'], false);
